version = 0.1
[default.deploy.parameters]
stack_name = "sam-app-project-prod"
resolve_s3 = true
s3_prefix = "sam-app-project-prod"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
