AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-micronaut-addition
  Addition of 2 integers, SAM Template for lambda-micronaut

Globals:
  Function:
    Tracing: Active
    CodeUri: build/libs/DevopsProject-0.1-all.jar
    Runtime: java17
    Timeout: 30
    MemorySize: 1024

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Name: SM703 Devops-project
      Auth:
        DefaultAuthorizer: NONE
        AddDefaultAuthorizerToCorsPreflight: false
      DefinitionBody:
        swagger: "2.0"
        info:
          title: "Addition"
        paths:
          /add/{num1}/{num2}:
            get:
              responses:
                '200':
                  description: OK
              x-amazon-apigateway-integration:
                type: aws_proxy
                uri: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AdditionFunctionProd.Arn}/invocations
                httpMethod: GET
                passthroughBehavior: WHEN_NO_MATCH
                responses:
                  default:
                    statusCode: '200'

  AdditionFunctionProd:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.micronaut.function.aws.proxy.MicronautLambdaHandler
      Policies:
      Events:
        GetAddition:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /add/{num1}/{num2}
            Method: get

  AdditionFunctionLogGroupProd:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${AdditionFunctionProd}"
      RetentionInDays: 7

Outputs:
  MicronautApiEndpoint:
    Description: "API Gateway endpoint URL for Prod stage for Micronaut sample function"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
