name: Java CI with Gradle to AWS - Production

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: change permission
        run: chmod +x gradlew
      - name: Configure AWS and SAM
        uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Build with Gradle and Run SonarQube analysis
        run: |
          ./gradlew build sonarqube -Dsonar.projectKey=tolunayg_sm703-devops-project -Dsonar.organization=tolunayg -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}


      - name: Check SonarCloud quality gate
        run: |
          sonar_project_key="tolunayg_sm703-devops-project"
          sonar_organization="tolunayg"
          sonar_host_url="https://sonarcloud.io"
          sonar_token="${{ secrets.SONAR_TOKEN }}"

          response=$(curl -s -u "${sonar_token}:" "${sonar_host_url}/api/qualitygates/project_status?projectKey=${sonar_project_key}&organization=${sonar_organization}")
          status=$(echo "$response" | jq -r '.projectStatus.status')

          if [[ "$status" != "OK" ]]; then
            echo "SonarCloud quality gate check failed. Failing the build."
            exit 1
          fi

      - name: Deploy with SAM
        run: |
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-file samconfig-prod.toml
          sam_app_name=$(grep -oP '(?<=Successfully created/updated stack - ).*' sam_deploy_output.txt | awk '{print $1}')
          echo "::set-output name=sam_app_name::$sam_app_name"

      - name: Check CloudWatch Alarm
        run: |
          sam_app_name="${{ steps.sam_deploy.outputs.sam_app_name }}"

          alarm_name="$sam_app_name"

          aws cloudwatch describe-alarms --alarm-names "$alarm_name" --query "MetricAlarms[?AlarmName=='$alarm_name']" --output json > /tmp/alarm

          exists=$(jq '. | length' /tmp/alarm)

          if [[ $exists -eq 0 ]]; then
            echo "CloudWatch alarm doesn't exist. Creating a new alarm."
            aws cloudwatch put-metric-alarm \
              --alarm-name "$alarm_name" \
              --alarm-description "Invocation Count Alarm" \
              --namespace AWS/Lambda \
              --metric-name Invocations \
              --dimensions Name=FunctionName,Value="$sam_app_name" \
              --statistic Sum \
              --period 300 \
              --threshold 1 \
              --evaluation-periods 1 \
              --comparison-operator GreaterThanThreshold
          else
            echo "CloudWatch alarm exists."
          fi