name: Java CI with Gradle to AWS - Production

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: change permission
        run: chmod +x gradlew
      - name: Configure AWS and SAM
        uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Build with Gradle and Run SonarQube analysis
        run: |
          ./gradlew build sonarqube -Dsonar.projectKey=tolunayg_sm703-devops-project -Dsonar.organization=tolunayg -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Run OWASP Dependency Check
        run: ./gradlew dependencyCheckAnalyze

      - name: Check OWASP Dependency Check results
        id: check-results
        run: |
          dependency_check_report="./build/reports/dependency-check-report.html"
          if [ -f "$dependency_check_report" ]; then
            echo "OWASP Dependency Check report found. Uploading..."
            echo "::set-output name=dependency-check-report-path::$dependency_check_report"
            vulnerable_count=$(grep -c '<vulnerability' "$dependency_check_report")
            if [[ $vulnerable_count -gt 0 ]]; then
              echo "OWASP Dependency Check found $vulnerable_count vulnerabilities. Failing the build."
              exit 1
            fi
          else
            echo "OWASP Dependency Check report not found."
            exit 1
          fi

      - name: Upload OWASP Dependency Check report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: ${{ steps.check-results.outputs.dependency-check-report-path }}


      - name: Deploy with SAM
        run:  sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-file samconfig-prod.toml
